import { Injectable, Inject, BadRequestException } from '@nestjs/common';
import Redis from 'ioredis';
import * as crypto from 'crypto';
import { unsafeUnscopedClient } from '@platform/db';

export const REDIS_CONNECTION = 'REDIS_CONNECTION';

function base64url(str: string | Buffer): string {
  const buf = typeof str === 'string' ? Buffer.from(str) : str;
  return buf.toString('base64')
    .replace(/=/g, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
}

function generateGitHubJWT(appId: string, privateKeyBase64: string): string {
  const privateKeyPem = Buffer.from(privateKeyBase64, 'base64').toString('utf8');
  const header = { alg: 'RS256', typ: 'JWT' };
  const now = Math.floor(Date.now() / 1000);
  const payload = {
    iat: now - 60, // clock skew leeway
    exp: now + (10 * 60), // 10-minute expiry
    iss: appId,
  };

  const headerB64 = base64url(JSON.stringify(header));
  const payloadB64 = base64url(JSON.stringify(payload));
  const message = `${headerB64}.${payloadB64}`;

  const signer = crypto.createSign('RSA-SHA256');
  signer.update(message);
  const signature = base64url(signer.sign(privateKeyPem));

  return `${message}.${signature}`;
}

function serializeInstallation(inst: any) {
  if (!inst) return null;
  return {
    ...inst,
    installationId: inst.installationId.toString(),
  };
}

@Injectable()
export class GithubService {
  constructor(
    @Inject(REDIS_CONNECTION) private readonly redis: Redis,
  ) {}

  private getAppJWT(): string {
    const appId = process.env.GITHUB_APP_ID;
    const privateKeyBase64 = process.env.GITHUB_APP_PRIVATE_KEY_BASE64;
    
    if (!appId || !privateKeyBase64) {
      throw new Error('GitHub App credentials are missing from environment.');
    }
    
    return generateGitHubJWT(appId, privateKeyBase64);
  }

  async getInstallationToken(installationId: string): Promise<string> {
    const tokenKey = `github:installation:${installationId}:token`;
    const lockKey = `github:installation:${installationId}:lock`;

    // 1. Check cache first
    let token = await this.redis.get(tokenKey);
    if (token) {
      return token;
    }

    // 2. Race condition protection: NX lock with 15s expiry
    const acquired = await this.redis.set(lockKey, 'locked', 'PX', 15000, 'NX');

    if (acquired === 'OK') {
      try {
        // Double-check cache in case another worker just finished
        token = await this.redis.get(tokenKey);
        if (token) {
          return token;
        }

        // 3. Exchange installation token from GitHub
        const jwt = this.getAppJWT();
        const response = await fetch(
          `https://api.github.com/app/installations/${installationId}/access_tokens`,
          {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${jwt}`,
              Accept: 'application/vnd.github+json',
              'X-GitHub-Api-Version': '2022-11-28',
              'User-Agent': 'incident-triage-agent',
            },
          }
        );

        if (!response.ok) {
          const errText = await response.text();
          throw new Error(`Failed to exchange installation token: ${response.status} - ${errText}`);
        }

        const data = await response.json();
        const freshToken = data.token;
        if (!freshToken) {
          throw new Error('No token field returned by GitHub.');
        }

        // Cache in Redis with 55-minute TTL (token expires at 60 mins)
        await this.redis.set(tokenKey, freshToken, 'EX', 55 * 60);
        return freshToken;
      } finally {
        // Release lock
        await this.redis.del(lockKey);
      }
    } else {
      // 4. Poll Redis for token generated by other worker
      const maxRetries = 20; // 10 seconds total wait
      for (let i = 0; i < maxRetries; i++) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        token = await this.redis.get(tokenKey);
        if (token) {
          return token;
        }
      }
      throw new Error(`Timeout waiting for concurrent token refresh on installation ${installationId}`);
    }
  }

  async bindInstallation(organizationId: string, installationIdStr: string, setupAction: string) {
    const installationId = BigInt(installationIdStr);
    
    // Check if the installation is already bound to a different organization
    const existing = await unsafeUnscopedClient.githubInstallation.findUnique({
      where: { installationId },
    });

    if (existing && existing.organizationId !== organizationId) {
      throw new BadRequestException('Security violation: This GitHub App installation is already bound to another organization.');
    }

    // Fetch installation details from GitHub to populate DB
    const jwt = this.getAppJWT();
    const response = await fetch(
      `https://api.github.com/app/installations/${installationId}`,
      {
        headers: {
          Authorization: `Bearer ${jwt}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'User-Agent': 'incident-triage-agent',
        },
      }
    );

    if (!response.ok) {
      throw new Error(`Failed to fetch installation details from GitHub: ${response.status}`);
    }

    const data = await response.json();
    const login = data.account.login;
    const type = data.account.type;
    const repoSelection = data.repository_selection;

    // Upsert GithubInstallation under active organization
    const inst = await unsafeUnscopedClient.githubInstallation.upsert({
      where: { installationId },
      update: {
        organizationId,
        accountLogin: login,
        accountType: type,
        repositorySelection: repoSelection,
        suspendedAt: null,
      },
      create: {
        id: crypto.randomUUID(),
        installationId,
        organizationId,
        accountLogin: login,
        accountType: type,
        repositorySelection: repoSelection,
        createdAt: new Date(),
      },
    });

    return serializeInstallation(inst);
  }

  async listRepositoriesByOrg(organizationId: string) {
    // Find the active GitHub installation for this organization
    const installation = await unsafeUnscopedClient.githubInstallation.findFirst({
      where: { organizationId, suspendedAt: null },
    });

    if (!installation) {
      return [];
    }

    const token = await this.getInstallationToken(installation.installationId.toString());
    
    const response = await fetch(
      `https://api.github.com/installation/repositories`,
      {
        headers: {
          Authorization: `token ${token}`,
          Accept: 'application/vnd.github+json',
          'X-GitHub-Api-Version': '2022-11-28',
          'User-Agent': 'incident-triage-agent',
        },
      }
    );

    if (!response.ok) {
      throw new Error(`Failed to fetch repositories from GitHub: ${response.status}`);
    }

    const data = await response.json();
    
    return (data.repositories || []).map((r: any) => ({
      id: r.id,
      name: r.name,
      full_name: r.full_name,
      private: r.private,
    }));
  }

  async processWebhook(rawBody: any, signatureHeader: string) {
    if (!Buffer.isBuffer(rawBody)) {
      throw new BadRequestException('Invalid request body parsing.');
    }

    const secret = process.env.GITHUB_APP_WEBHOOK_SECRET;
    if (!secret) {
      throw new Error('GITHUB_APP_WEBHOOK_SECRET is not configured in the environment.');
    }

    // Verify HMAC-SHA256 signature
    const hmac = crypto.createHmac('sha256', secret);
    hmac.update(rawBody);
    const computedSignature = 'sha256=' + hmac.digest('hex');

    const computedBuffer = Buffer.from(computedSignature);
    const receivedBuffer = Buffer.from(signatureHeader || '');

    if (
      computedBuffer.length !== receivedBuffer.length ||
      !crypto.timingSafeEqual(computedBuffer, receivedBuffer)
    ) {
      throw new BadRequestException('Invalid signature matching.');
    }

    let payload: any;
    try {
      payload = JSON.parse(rawBody.toString('utf8'));
    } catch (e) {
      throw new BadRequestException('Malformed JSON payload.');
    }

    const installationId = payload.installation?.id;
    if (!installationId) {
      return;
    }

    const instId = BigInt(installationId);
    const action = payload.action;

    // Handle installation lifecycle events
    if (payload.installation) {
      if (action === 'created') {
        const login = payload.installation.account.login;
        const type = payload.installation.account.type;
        const repoSelection = payload.installation.repository_selection;
        
        const existing = await unsafeUnscopedClient.githubInstallation.findUnique({
          where: { installationId: instId },
        });

        if (existing) {
          await unsafeUnscopedClient.githubInstallation.update({
            where: { installationId: instId },
            data: {
              accountLogin: login,
              accountType: type,
              repositorySelection: repoSelection,
              suspendedAt: null,
            },
          });
        }
      } else if (action === 'deleted') {
        const existing = await unsafeUnscopedClient.githubInstallation.findUnique({
          where: { installationId: instId },
        });

        if (existing) {
          const orgId = existing.organizationId;
          
          // Deletion ARCHIVES dependent Projects, never orphans them
          await unsafeUnscopedClient.project.updateMany({
            where: {
              organizationId: orgId,
              githubRepoId: { not: null },
            },
            data: {
              archivedAt: new Date(),
            },
          });

          await unsafeUnscopedClient.githubInstallation.delete({
            where: { installationId: instId },
          });
        }
      } else if (action === 'suspend') {
        await unsafeUnscopedClient.githubInstallation.updateMany({
          where: { installationId: instId },
          data: {
            suspendedAt: new Date(),
          },
        });
      } else if (action === 'unsuspend') {
        await unsafeUnscopedClient.githubInstallation.updateMany({
          where: { installationId: instId },
          data: {
            suspendedAt: null,
          },
        });
      }
    }

    // Handle installation_repositories event
    if (payload.repositories_removed && action === 'removed') {
      const existing = await unsafeUnscopedClient.githubInstallation.findUnique({
        where: { installationId: instId },
      });

      if (existing) {
        const orgId = existing.organizationId;
        const removedIds = payload.repositories_removed.map((r: any) => BigInt(r.id));
        
        await unsafeUnscopedClient.project.updateMany({
          where: {
            organizationId: orgId,
            githubRepoId: { in: removedIds },
          },
          data: {
            archivedAt: new Date(),
          },
        });
      }
    }
  }
}
